# frozen_string_literal: true
require 'spec_helper'

describe BrotherEscp::Image do
  it 'is inspectable' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png')).convert
    expect(STDOUT).to receive(:puts).at_least(:once)
    image.inspect
  end

  it 'Accept sequences and translate them in simgle density' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png'))

    data = Base64.strict_encode64(image.convert.to_escp)
    expected_result = 'GyoAZAD/gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgID/DQobKgBkAP8AAAAAf39/AwMDA39/fwADBw0NDQ0PAwD//wD///8ABw8MDAwOBwMAAAAAAAAAAAAAQGB/f2BADw8PDAwPDw8MDA8PAQAMDQ0NDQ8HAAMPDgwMDA8PAAcPDQ0NDwcDAAAAAP8NChsqAGQA/wAAAAD4+PgAAAAA+Pj4AOD4uJicnJiYAPj4APj4+MDw+BgMGDj44AEfPjgAAAAAAAAIGPj4GAj4+PgAAPj4+AAA+Pj4IPj4nJiY+PgA8Ps7GRs///yA8PiYmJyYmJAAAAAA/w0KGyoAZAD/AAAAAAAAAAAAAAAAAAAAAAMPDg8DAAAAAQEBAQEBAQAAAAEBAQEfHw8AAAAAAA4PBwAAAw8PDwAAAA8PCAABAQEBAQEAAAEBAAEBAAABAYGBnx8AAAAAAAAAAAAAAAAAAAD/DQobKgBkAP8AAAAAAAAAAAAAAAAAAQ9/+NgY2Px/DwH//8CAgP//Pxj+/4ODg////wAAAAAAAOD+Px/+4ID4fw//+IAAfv/Dg4OD/34A///AgIB8/++Dg4P//wAAAAAAAAAAAAAAAAAAAP8NChsqAGQA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAAAAAAAAAAAAAAAAAAAAAAAAA/w0KGyoAZADAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDADQo='

    expect(data).to eql(expected_result)
  end

  it 'Accept sequences and translate them in high density' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png'), converter: :high_density)

    data = Base64.strict_encode64(image.convert.to_escp)
    expected_result = 'GyonZAD///+AAACAAACAAACAAACAf/iAf/iAf/iAAwCAAwCAAwCAAwCAf/iAf/iAf/iAAACAA+CAB/iADbiADZiADZyADZyAD5iAA5iAAACA//iA//iAAACA//iA//iA//iAAMCAB/CAD/iADBiADAyADBiADjiAB/iAA+CAAAGAAB+AAD6AADiAAACAAACAAACAAACAAACAAACAQAiAYBiAf/iAf/iAYBiAQAiAD/iAD/iAD/iADACADACAD/iAD/iAD/iADACADACAD/iAD/iAAfiAACCADPiADfiADZyADZiADZiAD/iAB/iAAACAA/CAD/uADjuADBmADBuADD+AD/+AD/yAAICAB/CAD/iADZiADZiADZyAD5iAB5iAA5CAAACAAACAAACAAAD///8NChsqJ2QA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAA8AAH8AA/gAD9gADhgAD9gAA/wAAH8AAA8AAAEAAf8AAf8AAcAAAYAAAYAAAf8AAf8AAD8AABgAAP4AAf8AAYOAAYOAAYMAH/8AH/8AD/8AAAAAAAAAAAAAAAAAAAAADgAAD+AAB/4AAD8AAB8AA/4AD+AAD4AAD/gAAH8AAA8AAP8AD/gAD4AACAAAAH4AAf8AAcMAAYOAAYOAAYMAAf8AAH4AAAAAAf8AAf8AAMAAAYAAAYAAAHwAAP8AAe8AAYOAgYOAgYMAn/8AH/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////DQobKidkAMAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAMAAAA0K'

    expect(data).to eql(expected_result)
  end

  it 'Accept sequences and translate them in higher density' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png'), converter: :higher_density)

    data = Base64.strict_encode64(image.convert.to_escp)
    expected_result = 'GypIZAD///////+AAAAAAACAAAAAAACAAAAAAACAAAAAAACAf/gAAACAf/gAAACAf/gAAACAAwAAAACAAwAAAACAAwAAAACAAwAAAACAf/gAAACAf/gAAACAf/gAAQCAAAAADwCAA+AAfwCAB/gD+ACADbgP2ACADZgOGACADZwP2ACADZwD/ACAD5gAfwCAA5gADwCAAAAAAQCA//gB/wCA//gB/wCAAAABwACA//gBgACA//gBgACA//gB/wCAAMAB/wCAB/AAPwCAD/gAGACADBgA/gCADAwB/wCADBgBg4CADjgBg4CAB/gBgwCAA+Af/wCAAAEf/wCAAB8P/wCAAD4AAACAADgAAACAAAAAAACAAAAAAACAAAAAAACAAAAOAACAAAAP4ACAAAAH/gCAQAgAPwCAYBgAHwCAf/gD/gCAf/gP4ACAYBgPgACAQAgP+ACAD/gAfwCAD/gADwCAD/gA/wCADAAP+ACADAAPgACAD/gIAACAD/gAfgCAD/gB/wCADAABwwCADAABg4CAD/gBg4CAD/gBgwCAAfgB/wCAACAAfgCADPgAAACADfgB/wCADZwB/wCADZgAwACADZgBgACAD/gBgACAB/gAfACAAAAA/wCAA/AB7wCAD/sBg4CADjuBg4CADBmBgwCADBuf/wCADD8f/wCAD/8AAACAD/wAAACAAIAAAACAB/AAAACAD/gAAACADZgAAACADZgAAACADZwAAACAD5gAAACAB5gAAACAA5AAAACAAAAAAACAAAAAAACAAAAAAACAAAAAAAD///////8NChsqSGQAwAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAwAAAAAAADQo='

    expect(data).to eql(expected_result)
  end
end
