# frozen_string_literal: true
require 'spec_helper'

describe BrotherEscp::Image do
  it 'is inspectable' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png')).convert
    expect(STDOUT).to receive(:puts).at_least(:once)
    image.inspect
  end

  it 'Accept sequences and translate them in simgle density' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png'))

    data = Base64.strict_encode64(image.convert.to_escp)
    expected_result = 'GyoAZAD/gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgID/DQobKgBkAP8AAAAAAH8DAgICAgJ/AAABBwwICAwHAQB/fwAAfwAAAwYMCAgMBwAAAAAAAAAAAAAAAEB/f0AAAA8EDAgMBwQMCAwHAAAADAgJDQcDAAEHDAgIDA8AAAMHDAgIDAcAAAAAAP8NChsqAGQA/wAAAAAA+AAAAAAAAPgAAODwmIiIiJiAAPj4AAD4AADgeAgICBjwgAAPHBAAAAAAAAAACPj4CAAA+AAAAAD4AAAAAPgAAHDYiIgY+PgA4PEZGRkT/gAA4PCYiIiImAAAAAAA/w0KGyoAZAD/AAAAAAAAAAAAAAAAAAAAAAEPDA8BAAAAAAEAAQEBAAAAAAABAQEBDwAAAAAAAAgPAQAAAA8OAwAAAAcOAAAAAQEBAQAAAAABAAEBAAAAAQEBDw8AAAAAAAAAAAAAAAAAAAD/DQobKgBkAP8AAAAAAAAAAAAAAAAAAAc++JgYmPg+BwD//4CAAID/AAB+54EBAYP/AAAAAAAAAID4Hw/4gADwPwd+4AAAfP6DAQGD/nwA//+AgIAQ/sOBAYP//wAAAAAAAAAAAAAAAAAAAP8NChsqAGQA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w0K'

    expect(data).to eql(expected_result)
  end

  it 'Accept sequences and translate them in high density' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png'), converter: :high_density)

    data = Base64.strict_encode64(image.convert.to_escp)
    expected_result = 'GyonZAD///+AAACAAACAAACAAACAAACAf/iAAwCAAgCAAgCAAgCAAgCAAgCAf/iAAACAAACAAeCAB/CADJiACIiACIiADIiAB5iAAYCAAACAf/iAf/iAAACAAACAf/iAAACAAACAA+CABniADAiACAiACAiADBiAB/CAAICAAACAAA+AAByAABCAAACAAACAAACAAACAAACAAACAAACAQAiAf/iAf/iAQAiAAACAAACAD/iABACADACACACADACAB/iABACADACACACADACAB/iAAACAAACAAHCADNiACIiACYiADRiAB/iAA/iAAACAAeCAB/GADBmACBmACBmADBOAD/6AAACAAACAA+CAB/CADJiACIiACIiADIiAB5iAAACAAACAAACAAACAAAD///8NChsqJ2QA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAD4AAfgAD5gADBgAD5gAAfgAAD4AAAcAAAAAAP8AAf8AAIAAAYAAAQAAAYAAAP8AAAAAAAAAAH4AAOcAAYEAAQEAAQEAAYMAD/8AAAAAAAAAAAAAAAAAAAAAAAAACAAAD4AAAfgAAB8AAA8AAPgAD4AADgAAA/AAAD8AAAcAAH4AB+AADgAAAAAAAHwAAP4AAYMAAQEAAQEAAYMAAP4AAHwAAAAAAP8AAf8AAIAAAYAAAYAAABAAAP4AAMMAAYEAAQEAAYMAD/8AD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////DQo='

    expect(data).to eql(expected_result)
  end

  it 'Accept sequences and translate them in higher density' do
    image = BrotherEscp::Image.new(file_name: File.join(__dir__, '../fixtures/small.png'), converter: :higher_density)

    data = Base64.strict_encode64(image.convert.to_escp)
    expected_result = 'GypIZAD///////+AAAAAAACAAAAAAACAAAAAAACAAAAAAACAAAAAAACAf/gAAACAAwAAAACAAgAAAACAAgAAAACAAgAAAACAAgAAAACAAgAAAACAf/gAAACAAAAAAACAAAAABwCAAeAAPgCAB/AB+ACADJgPmACACIgMGACACIgPmACADIgB+ACAB5gAPgCAAYAABwCAAAAAAACAf/gA/wCAf/gB/wCAAAAAgACAAAABgACAf/gBAACAAAABgACAAAAA/wCAA+AAAACABngAAACADAgAfgCACAgA5wCACAgBgQCADBgBAQCAB/ABAQCAAIABgwCAAAAP/wCAAA8AAACAABwAAACAABAAAACAAAAAAACAAAAAAACAAAAAAACAAAAIAACAAAAPgACAAAAB+ACAAAAAHwCAQAgADwCAf/gA+ACAf/gPgACAQAgOAACAAAAD8ACAAAAAPwCAD/gABwCABAAAfgCADAAH4ACACAAOAACADAAAAACAB/gAfACABAAA/gCADAABgwCACAABAQCADAABAQCAB/gBgwCAAAAA/gCAAAAAfACAAHAAAACADNgA/wCACIgB/wCACYgAgACADRgBgACAB/gBgACAA/gAEACAAAAA/gCAAeAAwwCAB/EBgQCADBkBAQCACBkBgwCACBkP/wCADBMP/wCAD/4AAACAAAAAAACAAAAAAACAA+AAAACAB/AAAACADJgAAACACIgAAACACIgAAACADIgAAACAB5gAAACAAAAAAACAAAAAAACAAAAAAACAAAAAAACAAAAAAAD///////8NCg=='

    expect(data).to eql(expected_result)
  end
end
