# frozen_string_literal: true
require 'spec_helper'

describe BrotherEscp::Document do
  it 'is inspectable' do
    doc = BrotherEscp::Document.new
    expect(doc.inspect).to_not be_empty
  end

  it 'Accept sequences and translate them' do
    doc = BrotherEscp::Document.new
    doc.line_feed_size = 8
    doc.sequence(:CTL_FF)
    doc.page_length = 50
    expect(doc.to_base64).to eql('G2lhABtAGzMIDBsoQwIAMgA=')
  end

  it 'Accept images and translate them' do
    doc = BrotherEscp::Document.new
    doc.image(file_name: File.join(__dir__, 'fixtures/small.png'))
    expect(doc.to_base64).to eql('G2lhABtAGyoAZAD/gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgID/DQobKgBkAP8AAAAAf39/AwMDA39/fwADBw0NDQ0PAwD//wD///8ABw8MDAwOBwMAAAAAAAAAAAAAQGB/f2BADw8PDAwPDw8MDA8PAQAMDQ0NDQ8HAAMPDgwMDA8PAAcPDQ0NDwcDAAAAAP8NChsqAGQA/wAAAAD4+PgAAAAA+Pj4AOD4uJicnJiYAPj4APj4+MDw+BgMGDj44AEfPjgAAAAAAAAIGPj4GAj4+PgAAPj4+AAA+Pj4IPj4nJiY+PgA8Ps7GRs///yA8PiYmJyYmJAAAAAA/w0KGyoAZAD/AAAAAAAAAAAAAAAAAAAAAAMPDg8DAAAAAQEBAQEBAQAAAAEBAQEfHw8AAAAAAA4PBwAAAw8PDwAAAA8PCAABAQEBAQEAAAEBAAEBAAABAYGBnx8AAAAAAAAAAAAAAAAAAAD/DQobKgBkAP8AAAAAAAAAAAAAAAAAAQ9/+NgY2Px/DwH//8CAgP//Pxj+/4ODg////wAAAAAAAOD+Px/+4ID4fw//+IAAfv/Dg4OD/34A///AgIB8/++Dg4P//wAAAAAAAAAAAAAAAAAAAP8NChsqAGQA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAICAAAAAAAAAAAAAAAAAAAAAAAAA/w0KGyoAZADAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDADQo=')
  end
end
